from __future__ import annotations

from typing import Optional, Protocol, Sequence

from astra.ir.models import IREdge, IRNode


class GraphStorageAdapter(Protocol):
    def connect(self) -> None: ...

    def disconnect(self) -> None: ...

    def write_nodes(self, nodes: Sequence[IRNode]) -> None: ...

    def write_edges(self, edges: Sequence[IREdge]) -> None: ...

    def update_nodes(self, nodes: Sequence[IRNode]) -> None: ...

    def update_edges(self, edges: Sequence[IREdge]) -> None: ...

    def delete_nodes(self, node_ids: Sequence[str]) -> None: ...

    def delete_edges(self, edge_ids: Sequence[str]) -> None: ...


class GraphPass(Protocol):
    name: str

    def run(self, graph: "KnowledgeGraph") -> "KnowledgeGraph": ...


class GraphPassRegistry(Protocol):
    def register(self, graph_pass: GraphPass) -> None: ...

    def unregister(self, name: str) -> None: ...

    def passes(self) -> Sequence[GraphPass]: ...


class KnowledgeGraph(Protocol):
    def add_nodes(self, nodes: Sequence[IRNode]) -> None: ...

    def add_edges(self, edges: Sequence[IREdge]) -> None: ...

    def remove_nodes(self, node_ids: Sequence[str]) -> None: ...

    def remove_edges(self, edge_ids: Sequence[str]) -> None: ...

    def get_node(self, node_id: str) -> IRNode | None: ...

    def neighbors(self, node_id: str) -> Sequence[IRNode]: ...

    def outgoing(self, node_id: str) -> Sequence[IREdge]: ...

    def incoming(self, node_id: str) -> Sequence[IREdge]: ...

    def shortest_path(
        self,
        source: str,
        target: str,
    ) -> Sequence[str]: ...


class GraphQueryEngine(Protocol):
    def find_dependencies(self, node_id: str) -> Sequence[IRNode]: ...

    def find_dependents(self, node_id: str) -> Sequence[IRNode]: ...

    def shortest_path(self, src: str, dst: str) -> Optional[Sequence[str]]: ...

    def impact_analysis(self, node_id: str, depth: int = 3) -> Sequence[IRNode]: ...

    def extract_subgraph(
        self,
        node_ids: Sequence[str],
    ) -> Sequence[IREdge]: ...
