from __future__ import annotations

from typing import Protocol, Sequence, Optional
from astra.ir.models import IRNode, IREdge

class GraphStorageAdapter(Protocol):
    """Protocol for graph storage backends."""
    
    def connect(self) -> None: ...
    def close(self) -> None: ...
    
    # Node Operations
    def add_node(self, node: IRNode) -> None: ...
    def get_node(self, node_id: str) -> Optional[IRNode]: ...
    def delete_node(self, node_id: str) -> None: ...
    
    # Edge Operations
    def add_edge(self, edge: IREdge) -> None: ...
    def get_edges(self, from_node: Optional[str] = None, to_node: Optional[str] = None) -> Sequence[IREdge]: ...
    
    # Query Operations
    def get_all_nodes(self) -> Sequence[IRNode]: ...
    def get_all_edges(self) -> Sequence[IREdge]: ...
